from __future__ import annotations

from ..model import Manifest


def metadata_comments(manifest: Manifest, prefix: str = "#") -> list[str]:
    lines = [f"{prefix}!name={manifest.name}"]
    if manifest.description:
        lines.append(f"{prefix}!desc={manifest.description}")
    if manifest.author:
        lines.append(f"{prefix}!author={manifest.author}")
    if manifest.homepage:
        lines.append(f"{prefix}!homepage={manifest.homepage}")
    lines.append(f"{prefix} Generated by rewrite-converter; edit the canonical manifest, not this file.")
    return lines


def tag_for(manifest: Manifest, index: int, explicit: str) -> str:
    return explicit or f"{manifest.name} #{index + 1}"

